"""Added messages table

Revision ID: 119d680d253a
Revises: bd7d4d57d23b
Create Date: 2021-06-01 11:27:29.596723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119d680d253a'
down_revision = 'bd7d4d57d23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
