"""Added notifications table

Revision ID: b5a8f69a4866
Revises: 2fa2a7179122
Create Date: 2021-05-31 22:40:52.231571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a8f69a4866'
down_revision = '2fa2a7179122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EVENT', 'MESSAGE', 'FRIENDSHIP', name='notificationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['recipient'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
