"""Update account table, make all fields as possible nullable

Revision ID: b780da3a9f76
Revises: 98b9d9b3d066
Create Date: 2021-06-02 12:40:00.837597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b780da3a9f76'
down_revision = '98b9d9b3d066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('accounts', 'surname',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'surname',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###
