"""Added friend-invite table

Revision ID: cbf9c9f4f218
Revises: b5a8f69a4866
Create Date: 2021-05-31 22:50:52.071863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf9c9f4f218'
down_revision = 'b5a8f69a4866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user', sa.Integer(), nullable=False),
    sa.Column('to_user', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_invites')
    # ### end Alembic commands ###
