"""Added start_date field to events table

Revision ID: e7c0b85fe40d
Revises: b780da3a9f76
Create Date: 2021-07-14 18:15:17.820008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c0b85fe40d'
down_revision = 'b780da3a9f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'start_date')
    # ### end Alembic commands ###
