"""add confirmation_email field to User table

Revision ID: 016912c0b14a
Revises: 1d2a63d0615c
Create Date: 2023-03-08 11:38:25.770991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016912c0b14a'
down_revision = '1d2a63d0615c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_token')
    # ### end Alembic commands ###
