"""Added column is_notified to users table

Revision ID: 604d7420855b
Revises: 8a564d5401cc
Create Date: 2022-09-14 10:34:05.309899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604d7420855b'
down_revision = '8a564d5401cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_notified', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_notified')
    # ### end Alembic commands ###
