"""Add members_count field

Revision ID: 6d8a3a7be9ff
Revises: 35849b940907
Create Date: 2022-02-09 09:22:50.919925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '6d8a3a7be9ff'
down_revision = '35849b940907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    members_quantity = postgresql.ENUM('2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '30', '40', '50', '1000', name='members_quantity')
    members_quantity.create(op.get_bind())
    op.add_column('events', sa.Column('members_count', sa.Enum('2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '30', '40', '50', '1000', name='members_quantity'), server_default='2', nullable=False))
    op.drop_column('events', 'is_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_group', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    members_quantity = postgresql.ENUM('2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '30', '40', '50', '1000', name='members_quantity')
    members_quantity.drop(op.get_bind())
