"""remove start_time field from event table

Revision ID: 74acbe81ec0f
Revises: c36fa8066abe
Create Date: 2021-07-15 17:09:27.720938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74acbe81ec0f'
down_revision = 'c36fa8066abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_time', postgresql.TIME(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
