"""Add UniqueConstraint to event_users table

Revision ID: 8a564d5401cc
Revises: b01a63f7c588
Create Date: 2022-02-11 10:17:36.876561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a564d5401cc'
down_revision = 'b01a63f7c588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('events_user', 'event_users', ['events_id', 'users_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_user', 'event_users', type_='unique')
    # ### end Alembic commands ###
