"""Add members_count fields

Revision ID: b01a63f7c588
Revises: 6d8a3a7be9ff
Create Date: 2022-02-09 14:46:43.539992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01a63f7c588'
down_revision = '6d8a3a7be9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
