"""Add type field to message model

Revision ID: c02acf96aa31
Revises: df691b2e90a2
Create Date: 2021-07-25 14:56:35.026922

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c02acf96aa31'
down_revision = 'df691b2e90a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    notification_type = postgresql.ENUM('EVENT', 'MESSAGE', 'FRIENDSHIP', name='notification_type')
    notification_type.create(op.get_bind())
    op.add_column('messages', sa.Column('type', sa.Enum('EVENT', 'MESSAGE', 'FRIENDSHIP', name='notification_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'type')
    notification_type = postgresql.ENUM('EVENT', 'MESSAGE', 'FRIENDSHIP', name='notification_type')
    notification_type.drop(op.get_bind())
    # ### end Alembic commands ###
