"""Return notification table

Revision ID: df691b2e90a2
Revises: 8723d14d5302
Create Date: 2021-07-19 22:38:44.250823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df691b2e90a2'
down_revision = '8723d14d5302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EVENT', 'MESSAGE', 'FRIENDSHIP', name='notificationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['recipient'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
